name: Push commit
on: workflow_dispatch
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      with:
        token: ${{ secrets.API_KEY }}
      - name: Create report file
        run: date +%s > report.txt
      - name: Commit report
        run: |
          git config --global user.name 'action man'
          git config --global user.email 'mail@susy.org'
          git add -A
          git commit -am "Automated report"
          git push
